pj4: part1 part2

part1:
	gcc -g Project4_part1.c -o va_space -pthread -D GNU_SOURCE

part2:
	gcc -g Project4_part2.c -o va_status -pthread -D GNU_SOURCE
clean:
	rm sequential paralell list-forming pc
